<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableMauiImageProcessing>false</EnableMauiImageProcessing>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.0.2" />
    <PackageReference Include="bunit" Version="2.8.6" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\PhilSLA.ExamPlatform.Candidate\PhilSLA.ExamPlatform.Candidate.csproj" />
    <ProjectReference Include="..\..\src\PhilSLA.ExamPlatform.Core\PhilSLA.ExamPlatform.Core.csproj" />
    <ProjectReference Include="..\..\src\PhilSLA.ExamPlatform.Infrastructure\PhilSLA.ExamPlatform.Infrastructure.csproj" />
  </ItemGroup>

</Project>
